services:
  - type: web
    name: nyvex
    repo: https://github.com/Beto321df/EnfuscacionLevel
    branch: main
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_SECRET
        sync: false
