services:
  - type: web
    name: nyvex
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: FIREBASE_SECRET
        sync: false
