const crypto=require('crypto');
const GROUP_SIZE=19,SEPARATOR='/ ',CHUNK_BYTES=30*1024;
const FIRST_PAIRS=[['0','仧'],['1','2'],['3','享'],['4','5'],['6','丿'],['7','8'],['9','些'],['!','@'],['#','$'],['%','^'],['&','*'],['(',')'],['+','='],['?',';'],[':','>'],['|','~']];
const SECOND_PAIRS=[['0','亝'],['1','2'],['3','严'],['4','5'],['6','仩'],['7','8'],['9','亁'],['!','@'],['#','$'],['%','^'],['&','*'],['(',')'],['+','='],['?',';'],[':','>'],['|','~']];
const FIRST=FIRST_PAIRS.flat(),SECOND=SECOND_PAIRS.flat(),OUTER_FIRST=FIRST.join(''),OUTER_SECOND=SECOND.join(''),OUTER_SYMBOLS=Array.from(new Set([...FIRST,...SECOND])),CJK_RE=/[\u4E00-\u9FFF]/u,CJK_GLYPH_COUNT_FIRST=FIRST.filter(c=>CJK_RE.test(c)).length,CJK_GLYPH_COUNT_SECOND=SECOND.filter(c=>CJK_RE.test(c)).length,CJK_GLYPH_COUNT=CJK_GLYPH_COUNT_FIRST+CJK_GLYPH_COUNT_SECOND;
if(FIRST.length!==32||SECOND.length!==32||new Set(FIRST).size!==32||new Set(SECOND).size!==32||CJK_GLYPH_COUNT_FIRST!==4||CJK_GLYPH_COUNT_SECOND!==4)throw new Error('Z visual alphabet inválido.');
function randomInt(min,max){return crypto.randomInt(min,max+1)}
function bytes(v){return Buffer.isBuffer(v)?Buffer.from(v):Buffer.from(String(v),'utf8')}
function encodeBytes(input){const source=bytes(input),state1=Array.from({length:16},()=>randomInt(0,1)),state2=Array.from({length:16},()=>randomInt(0,1));let out='',last='',lastPair='';for(const value of source){const hn=value>>>4&15,ln=value&15,a0=FIRST_PAIRS[hn],b0=SECOND_PAIRS[ln],c=[];for(let i=0;i<2;i++)for(let j=0;j<2;j++){const a=a0[(state1[hn]+i)&1],b=b0[(state2[ln]+j)&1],pen=(a===last?4:0)+(b===last?4:0)+(b===a?2:0)+(`${a}${b}`===lastPair?3:0);c.push([pen,a,b,i,j])}const best=Math.min(...c.map(x=>x[0])),opts=c.filter(x=>x[0]===best),pick=opts[randomInt(0,opts.length-1)];state1[hn]=(state1[hn]+pick[3]+1)&1;state2[ln]=(state2[ln]+pick[4]+1)&1;out+=pick[1]+pick[2];last=pick[2];lastPair=pick[1]+pick[2]}return out}
function decodeVisualText(input){const chars=Array.from(String(input||'')).filter(ch=>ch!=='/'&&!/\s/u.test(ch));if(chars.length%2)throw new Error('Z visual transport: longitud impar.');const first=new Map(FIRST.map((ch,index)=>[ch,index>>1])),second=new Map(SECOND.map((ch,index)=>[ch,index>>1])),out=Buffer.alloc(chars.length/2);for(let i=0,p=0;i<chars.length;i+=2,p++){const a=first.get(chars[i]),b=second.get(chars[i+1]);if(a===undefined||b===undefined)throw new Error('Z visual transport: glyph inválido.');out[p]=(a<<4)|b}return out}
function splitVisualLines(encoded,width=GROUP_SIZE){const chars=Array.from(String(encoded||'')),lines=[];for(let i=0;i<chars.length;i+=width)lines.push(chars.slice(i,i+width).join(''));return lines}
function encodeVisualChunk(input){const lines=splitVisualLines(encodeBytes(input));return{payload:lines.join(SEPARATOR),lines,cjkPerGroupTarget:CJK_GLYPH_COUNT/FIRST.length,cjkGlyphCount:CJK_GLYPH_COUNT}}
function encodeVisual(source){const sourceBytes=bytes(source),chunks=[],limit=Math.max(1,sourceBytes.length);for(let offset=0;offset<limit;offset+=CHUNK_BYTES)chunks.push(encodeVisualChunk(sourceBytes.subarray(offset,Math.min(offset+CHUNK_BYTES,sourceBytes.length))));const payload=chunks.map(part=>part.payload).join(SEPARATOR);return{v:9,w:GROUP_SIZE,separator:SEPARATOR,first:OUTER_FIRST,second:OUTER_SECOND,cjkGlyphsInFirstLane:CJK_GLYPH_COUNT_FIRST,cjkGlyphsInSecondLane:CJK_GLYPH_COUNT_SECOND,chunks:chunks.map(part=>part.payload),lines:chunks.flatMap(part=>part.lines),payload,chunkBytes:CHUNK_BYTES}}
function visualLoader(encoded){const p=encoded&&typeof encoded==='object'&&Array.isArray(encoded.chunks)?encoded:encodeVisual(encoded),q=v=>`[=[${String(v)}]=]`,P=q(p.chunks.join(SEPARATOR)),A=q(p.first||OUTER_FIRST),B=q(p.second||OUTER_SECOND);return`return(function(t,...)local l=t.L;local m=function(s)local z,i={},0;for _,c in utf8.codes(s)do z[c]=math.floor(i/2);i=i+1 end;return z end;local x,y=m(l[2]),m(l[3]);local r,h={},nil;for _,c in utf8.codes(l[1])do if c>32 and c~=47 then if h then r[#r+1]=string.char(h*16+y[c]);h=nil else h=x[c] end end end;local f=loadstring or load;assert(f,'Z3 loader unavailable');local c,e=f(table.concat(r));assert(c,e);return c(...) end)({L={${P},${A},${B}}},...)`}
function wrapVisual(source){return visualLoader(encodeVisual(source))}
function decodeVisual(encoded){return encoded&&typeof encoded==='object'&&Array.isArray(encoded.chunks)?decodeVisualText(encoded.chunks.join('')):decodeVisualText(encoded)}
module.exports={FIRST,SECOND,OUTER_FIRST,OUTER_SECOND,OUTER_SYMBOLS,CJK_GLYPH_COUNT,GROUP_SIZE,SEPARATOR,CHUNK_BYTES,encodeVisual,encodeVisualChunk,decodeVisual,decodeVisualText,visualLoader,wrapVisual,randomInt};