(()=>{
  const $=id=>document.getElementById(id); const MAX_LINES=5000, MAX_SCRIPTS=10;
  const APP_ORIGIN=(location.origin&&location.origin!=='null')?location.origin:'https://nyvex.onrender.com';
  const API_BASE=APP_ORIGIN.replace(/\/$/,'');
  const OBFUSCATE_URL=`${API_BASE}/api/obfuscate`, SCRIPT_API_URL=`${API_BASE}/api/scripts`, LOAD_URL=id=>`${API_BASE}/api/get-script?id=${encodeURIComponent(id)}`;
  const firebaseConfig={apiKey:'AIzaSyD7tMMxK7f6X7c2uH2zXhWc7g2n8k1p3Q9',authDomain:'loaderz1.firebaseapp.com',databaseURL:'https://loaderz1-default-rtdb.firebaseio.com',projectId:'loaderz1',storageBucket:'loaderz1.firebasestorage.app',messagingSenderId:'421601823975',appId:'1:421601823975:web:9f0d4f22d2d2f2e1e2f3a4b'};
  try{if(!firebase.apps.length) firebase.initializeApp(firebaseConfig);}catch(e){}
  let currentUser=localStorage.getItem('z_current_user')||'', isMaster=localStorage.getItem('z_is_master')==='true', editId=''; let authMode='signin',pendingUser='',pendingPass='';
  function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}
  async function parseJsonResponse(res,label){
    const text=await res.text();
    if(!text.trim()) throw new Error(`${label} returned an empty response (HTTP ${res.status}) from ${res.url||'the Render API'}. The deployed service is not returning the Node JSON handler.`);
    try{return JSON.parse(text)}catch(e){throw new Error(`${label} returned invalid JSON (HTTP ${res.status}) from ${res.url||'the Render API'}.`)}
  }
  function clearAlert(id){$(id).innerHTML='';} function alertBox(id,msg,type='err'){$(id).innerHTML=`<div class="alert ${type}">${escapeHtml(msg)}</div>`}
  function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__ztoast);window.__ztoast=setTimeout(()=>t.classList.remove('show'),2400)}
  function loading(on,text='Working...'){$('loading').classList.toggle('hidden',!on);$('loading-text').textContent=text;}
  function setAuthTab(mode){authMode=mode;$('tab-signin').classList.toggle('active',mode==='signin');$('tab-signup').classList.toggle('active',mode==='signup');$('auth-desc').textContent=mode==='signup'?'Create your account with a username, password and 4-digit PIN.':'Enter your username, account password and 4-digit PIN.';$('auth-pass').value='';$('auth-pass').setAttribute('autocomplete',mode==='signup'?'new-password':'current-password');}
  function openAuth(){clearAlert('auth-alert');$('auth-user').value='';$('auth-pass').value='';$('auth-modal').classList.remove('hidden');setAuthTab(authMode);setTimeout(()=>$('auth-user').focus(),50)}
  function closeAuth(){pendingUser='';pendingPass='';$('auth-modal').classList.add('hidden')}
  async function startAuth(){const user=$('auth-user').value.trim();const pass=$('auth-pass').value;if(!user)return alertBox('auth-alert','Enter a username.');if(!/^[a-zA-Z0-9_-]{2,40}$/.test(user))return alertBox('auth-alert','Username must be 2–40 chars: letters, numbers, _ or -.');if(!pass)return alertBox('auth-alert','Enter your account password.');if(pass.length<4)return alertBox('auth-alert','Password must be at least 4 characters.');pendingUser=user;pendingPass=pass;$('auth-modal').classList.add('hidden');$('pin-alert').innerHTML='';document.querySelectorAll('.pin').forEach(x=>x.value='');$('pin-modal').classList.remove('hidden');setTimeout(()=>document.querySelector('.pin')?.focus(),50)}
  async function confirmPin(){const pin=[...document.querySelectorAll('.pin')].map(x=>x.value).join('');if(pin.length!==4)return alertBox('pin-alert','Enter the 4-digit PIN.');loading(true,authMode==='signup'?'Creating account...':'Checking credentials...');try{const res=await fetch(`${API_BASE}/api/login`,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({mode:authMode,user:pendingUser,pass:pendingPass,pin})});const data=await parseJsonResponse(res,'Login API');if(!res.ok||!data.ok)throw new Error(data.msg||'Authentication failed.');currentUser=pendingUser;isMaster=currentUser==='admin123';localStorage.setItem('z_current_user',currentUser);localStorage.setItem('z_is_master',String(isMaster));pendingPass='';$('pin-modal').classList.add('hidden');loading(false);go('dashboard')}catch(e){loading(false);alertBox('pin-alert',e.message||'Authentication error.')}}
  let lastDashboardLoad=0;
  function go(view){['login','dashboard','editor'].forEach(v=>{const el=$(`view-${v}`);if(el)el.classList.toggle('hidden',v!==view)});$('public-nav').classList.toggle('hidden',!!currentUser);$('private-nav').classList.toggle('hidden',!currentUser);if(currentUser)$('nav-user').textContent=currentUser;if(view==='dashboard'&&Date.now()-lastDashboardLoad>1000){lastDashboardLoad=Date.now();loadScripts()}}
  async function loadScripts(){const list=$('script-list');list.innerHTML='<div class="alert">Loading scripts...</div>';try{const res=await fetch(`${SCRIPT_API_URL}?user=${encodeURIComponent(currentUser)}`,{headers:{Accept:'application/json'}});const data=await parseJsonResponse(res,'Scripts API');if(!res.ok)throw new Error(data.msg||'Failed to load scripts');const scripts=data.scripts||{};const ids=Object.keys(scripts);$('slot-count').textContent=`${ids.length}/${MAX_SCRIPTS} slots used`;if(!ids.length){list.innerHTML='<div class="alert">$ no scripts found — create one below</div>';return}list.innerHTML=ids.map(id=>{const s=scripts[id]||{};return `<div class="script-row"><div class="script-meta"><strong>${escapeHtml(id)}</strong><span>Owner: ${escapeHtml(s.owner||currentUser)}</span></div><div class="script-actions"><button class="icon-btn" data-edit="${escapeHtml(id)}" title="Edit"><i class="fa-solid fa-gear"></i></button><button class="copy-btn" data-copy="${escapeHtml(id)}">Copy Link</button><button class="delete-btn" data-delete="${escapeHtml(id)}" title="Delete"><i class="fa-solid fa-trash"></i></button></div></div>`}).join('');list.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',()=>copyLoader(b.dataset.copy)));list.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>editScript(b.dataset.edit,scripts[b.dataset.edit])));list.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>deleteScript(b.dataset.delete)))}catch(e){$('slot-count').textContent='—';list.innerHTML='';alertBox('dash-alert',e.message||'Could not load scripts.')}}
  function copyLoader(id){const code=`loadstring(game:HttpGet("${LOAD_URL(id)}"))()`;copyText(code).then(()=>toast('Loadstring copied!')).catch(()=>alertBox('dash-alert','Copy failed.'))}
  async function editScript(id,data){editId=id;$('script-id').value=id;$('script-id').readOnly=true;$('script-code').value=typeof data?.source==='string'?data.source:(typeof data?.code==='string'?data.code:'');$('editor-eyebrow').textContent='// EDIT SCRIPT';$('editor-heading').textContent='Manage script';$('editor-state').textContent='EXISTING';clearAlert('editor-alert');updateCounter();go('editor')}
  async function deleteScript(id){if(!confirm(`Delete script "${id}"?`))return;loading(true,'Deleting script...');try{const res=await fetch(SCRIPT_API_URL,{method:'DELETE',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({user:currentUser,id})});const data=await parseJsonResponse(res,'Scripts API');if(!res.ok||!data.ok)throw new Error(data.msg||'Could not delete script.');loading(false);toast('Script deleted!');loadScripts()}catch(e){loading(false);alertBox('dash-alert',e.message||'Delete failed.')}}
  function newScript(){if(!isMaster){const countText=$('slot-count').textContent;const used=Number((countText.match(/^\d+/)||['0'])[0]);if(used>=MAX_SCRIPTS)return alertBox('dash-alert',`Limit reached: maximum ${MAX_SCRIPTS} scripts per account.`)}editId='';$('script-id').value='';$('script-id').readOnly=false;$('script-code').value='';$('editor-eyebrow').textContent='// NEW SCRIPT';$('editor-heading').textContent='Protect code';$('editor-state').textContent='READY';clearAlert('editor-alert');updateCounter();go('editor')}
  function updateCounter(){const n=Math.max(1,$('script-code').value.split('\n').length);$('line-counter').textContent=`Lines: ${n.toLocaleString()} / ${MAX_LINES}`;$('line-counter').style.color=n>MAX_LINES?'var(--red)':'var(--muted)'}
  async function obfuscateSource(source){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),60000);try{const res=await fetch(OBFUSCATE_URL,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({code:source}),signal:controller.signal});let data=null;try{data=await res.json()}catch(e){throw new Error('Obfuscation API returned invalid data.')}if(!res.ok||!data.success||typeof data.code!=='string'||!data.code.trim())throw new Error(data.error||'Obfuscation failed.');return {code:data.code,format:data.format||''};}catch(e){if(e&&e.name==='AbortError')throw new Error('Obfuscation timed out after 60 seconds.');throw e}finally{clearTimeout(timer)}}
  async function saveScript(){clearAlert('editor-alert');const id=$('script-id').value.trim(),source=$('script-code').value;if(!id||!source.trim())return alertBox('editor-alert','Fill all fields.');const clean=id.replace(/[^a-zA-Z0-9_-]/g,'');if(clean!==id)return alertBox('editor-alert','ID only allows letters, numbers, _ and -.');if(source.split('\n').length>MAX_LINES)return alertBox('editor-alert','Max 5,000 lines exceeded.');loading(true,'Generating Z3 visual protection...');try{const res=await fetch(SCRIPT_API_URL,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({user:currentUser,id:clean,code:source,source,isUpdate:Boolean(editId)})});const data=await parseJsonResponse(res,'Scripts API');if(!res.ok||!data.ok)throw new Error(data.msg||'Could not save script.');loading(false);$('script-code').value=source;updateCounter();toast(editId?'Script updated!':'Script protected and saved!');go('dashboard')}catch(e){loading(false);alertBox('editor-alert',e.message||'Save failed.')}}
  function copyText(text){if(navigator.clipboard&&window.isSecureContext)return navigator.clipboard.writeText(text);return new Promise((resolve,reject)=>{const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();try{document.execCommand('copy');resolve()}catch(e){reject(e)}finally{t.remove()}})}
  function logout(){localStorage.removeItem('z_current_user');localStorage.removeItem('z_is_master');currentUser='';isMaster=false;go('login');toast('Signed out.')}
  $('start-btn').onclick=openAuth;$('hero-login').onclick=openAuth;$('close-auth').onclick=closeAuth;$('tab-signin').onclick=()=>setAuthTab('signin');$('tab-signup').onclick=()=>setAuthTab('signup');$('auth-next').onclick=startAuth;$('toggle-password').onclick=()=>{const input=$('auth-pass');const button=$('toggle-password');const isPassword=input.type==='password';input.type=isPassword?'text':'password';button.innerHTML=isPassword?'<i class="fa-solid fa-eye-slash"></i>':'<i class="fa-solid fa-eye"></i>';button.setAttribute('aria-label',isPassword?'Hide password':'Show password')};$('auth-pass').addEventListener('keydown',e=>{if(e.key==='Enter')startAuth()});$('close-pin').onclick=()=>{$('pin-modal').classList.add('hidden')};$('confirm-pin').onclick=confirmPin;$('logout-btn').onclick=logout;$('new-script').onclick=newScript;$('cancel-editor').onclick=()=>go('dashboard');$('save-script').onclick=saveScript;$('script-code').addEventListener('input',updateCounter);document.querySelectorAll('.pin').forEach((box,i,all)=>{box.addEventListener('input',e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(-1);if(e.target.value&&i<3)all[i+1].focus()});box.addEventListener('keydown',e=>{if(e.key==='Backspace'&&!e.target.value&&i>0)all[i-1].focus();if(e.key==='Enter')confirmPin()})});if(currentUser)go('dashboard');else go('login');
})();
